encoding: UTF-8
gems: [jekyll-paginate]
permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: pygments
#pygments: true

# 作者信息
author: 
  name: 贺勇
  email: heyongsheng@gmail.com
  link: http://heystc.github.io/
  #weibo: http://weibo.com/u/2344559062
  github: https://github.com/heystc
  github_username: heystc
  #weibo_username: heystc

duoshuo_query:
  short_name: heys

# 站点信息
title : TBD
description: 
  一不小心迈入计算机行业，在程序猿的道路上艰难地前行，目标是成
  为一名优秀的全栈工程师或者说资深码农。
  对很多东西都充满兴趣，跑步游泳，近期目标是能跑半程马拉松，学会自由泳。
  
#baseurl: http://heystc.github.io
url: http://heystc.github.io/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/gavatar.png
favicon : /assets/img/favicon.png

# disqus 设置
# disqus:
#  shortname: heystc

#profile 个人信息

profile_desc : 一切好的友谊，都是自然而然形成的。再好的朋友也应该有距离，太热闹的友谊往往就是空洞而且是无物的。<br>

# 首页除了最新文章外显示分类
cates: 
- Essay
# - Python
# - OpenStack

# 中文本地化
locals: 
   newest : 最新文章